Add asian-southeast1 to RTDB CLI
firebase/firebase-tools pull request #3460
Opened 2021-06-07 18:46 UTC by fredzqm

### Description

### Scenarios Tested

### Sample Commands

2021-06-07 19:20 UTC, fredzqm commented
Any idea why CI is failing. Did I forget to update in some places?

2021-06-07 19:59 UTC, bkendall requested changes

2021-06-07 19:59 UTC, bkendall commented on src/management/database.ts
> +  ASIAN_SOUTHEAST1 = "asia-southeast1",
The enum should match the name

```suggestion
  ASIA_SOUTHEAST1 = "asia-southeast1",
```

2021-06-07 19:59 UTC, bkendall commented on src/management/database.ts
> +        `Unexpected location value: ${location}. Only us-central1, europe-west1 and asia-southeast1 locations are supported`
I like oxford commas?

```suggestion
        `Unexpected location value: ${location}. Only us-central1, europe-west1, and asia-southeast1 locations are supported`
```

2021-06-07 19:59 UTC, bkendall commented on CHANGELOG.md
> +- Add Singapore (asia-southeast1) to Firebase Database location.
```suggestion
- Add Singapore (asia-southeast1) as a valid Firebase Realtime Database location.
```

2021-06-07 20:03 UTC, fredzqm commented on src/management/database.ts
> +  ASIAN_SOUTHEAST1 = "asia-southeast1",
Oh, sorry, meant to keep them the same.

2021-06-07 22:40 UTC, bkendall approved these changes
LGTM, but take a look at the tests please :)

2021-06-07 23:25 UTC, fredzqm commented
@bkendall I am suspecting the last commit https://github.com/firebase/firebase-tools/pull/3454 broken the CI build.
After I revert it on top of the this PR, all tests passes now: https://github.com/firebase/firebase-tools/pull/3461

2021-06-08 01:12 UTC, inlined commented
Fix for the build break incoming.

2021-06-08 11:38 UTC, samtstern approved these changes

2021-06-08 11:39 UTC, merged