Set maximum backoff to 10s for OperationPoller
firebase/firebase-tools pull request #3685
Opened 2021-08-14 01:25 UTC by kaibolay

Previously it used 60s (which is the default).

This change doesn't make much of a difference when using the default timeout of 30s, but for longer timeouts it still makes sense to poll frequently to minimize excessive delays for interactive (human) users.

2021-08-16 20:39 UTC, lfkellogg commented
LGTM. Agreed that 10 seconds seems like a more appropriate max backoff when polling in a CLI tool.

2021-08-16 20:55 UTC, bkendall requested changes
1. Could you adjust this change to have an added field in `OperationPollerOptions` for maximum backoff, and set that option where a shorter max backoff would be useful? That way we don't have to audit all the places where this poller is used and make a determination about each one (it probably isn't many places, but I'm a little concerned about it). What do you think?
1. Please include a `CHANGELOG.md`

2021-08-16 22:26 UTC, lfkellogg commented
@bkendall Sounds good. I've put up a new PR with a change that doesn't actually modify the backoff of any existing calls, but will let us configure it on a new call we're adding: https://github.com/firebase/firebase-tools/pull/3687

2021-08-18 21:14 UTC, lfkellogg commented
Closing this in favor of https://github.com/firebase/firebase-tools/pull/3687

2021-08-18 21:14 UTC, closed without merging