Fix bug where callable functions can't be emulated.
firebase/firebase-tools pull request #4314
Opened 2022-03-16 22:51 UTC by taeold

Fixes https://github.com/firebase/firebase-tools/issues/4313

2022-03-16 23:32 UTC, bkendall requested changes

2022-03-16 23:32 UTC, bkendall commented on scripts/integration-helpers/framework.ts
> +    const url = `http://localhost:${[this.functionsEmulatorPort, this.project, zone, name].join(
This is real strange, just given how URLs should be thought of. Consider pulling the port out of the path:

```suggestion
    const url = `http://localhost:${this.functionsEmulatorPort}/${this.project, zone, name].join(
```

2022-03-16 23:32 UTC, bkendall commented on scripts/triggers-end-to-end-tests/functions/index.js
> +exports.oncallv2 = functionsV2.https.onCall((req) => {
`onCallv2` Doesn't match `onCall` above as written

2022-03-16 23:50 UTC, taeold commented on scripts/triggers-end-to-end-tests/functions/index.js
> +exports.oncallv2 = functionsV2.https.onCall((req) => {
v2 functions can't contain capital letters.

2022-03-17 00:12 UTC, bkendall approved these changes

2022-03-17 00:46 UTC, colerogers approved these changes

2022-03-17 01:19 UTC, merged

2022-03-17 21:44 UTC, BaptisteCool commented
Release in 1.4.0 google [here](https://github.com/firebase/firebase-tools/issues/4320)