Container contract updates
firebase/firebase-tools pull request #4388
Opened 2022-03-31 22:41 UTC by taeold

Partial revert of https://github.com/firebase/firebase-tools/pull/4240 where we transformed EventFilters to list of arrays. We now prefer to keep the object structure.

To support path-pattern operator on event filters, we add new eventFilterPathPattern property. While we are at it, we also adds channel property to event trigger definition.

Note that most of the affected changes are in test files :/

Relevant SDK change: https://github.com/firebase/firebase-functions/pull/1070

2022-03-31 23:45 UTC, colerogers requested changes
couple things, then we're g2g

2022-03-31 23:45 UTC, colerogers commented on src/deploy/functions/release/planner.ts
> +  return have.eventTrigger.eventFilters.topic !== want.eventTrigger.eventFilters.topcic;
typo - `topcic` to `topic`

2022-03-31 23:45 UTC, colerogers commented on src/deploy/functions/backend.ts
> +type EventFilterKey = "resource" | "topic" | "bucket" | "alerttype" | string;
while we're here, we can also add `appid` for alerts that use it

2022-03-31 23:53 UTC, colerogers approved these changes

2022-04-01 06:03 UTC, merged

2022-04-05 17:23 UTC, inlined reviewed
Woof. Lots of work all over again. TY for this.

2022-04-05 17:23 UTC, inlined commented on src/deploy/functions/backend.ts
> +type EventFilterKey = "resource" | "topic" | "bucket" | "alerttype" | string;
I wonder if it's silly to keep this type.

2022-04-05 17:23 UTC, inlined commented on src/gcp/cloudfunctionsv2.ts
> + *
wat