Use mebibytes over hybrid mega/mebi
firebase/firebase-tools pull request #4474
Opened 2022-04-25 17:57 UTC by inlined

V1 always used "Mebibytes" (base 2) but used the term "Megabytes" (ambiguous base 2 or 10) for a unitless "availableMemoryMb". In v2, the available memory field has units. In those units, "M" is base 10 and "Mi" is base 2.

This corrects the previous erroneous behavior where we had base 2 quantities and base 10 units.

2022-04-27 14:28 UTC, colerogers requested changes
lgtm, delete the empty comments before merge

2022-04-27 14:28 UTC, colerogers commented on src/gcp/cloudfunctionsv2.ts
> + */
Empty ts doc comment

2022-04-27 14:28 UTC, colerogers commented on src/gcp/cloudfunctionsv2.ts
> + */
Empty ts doc comment

2022-04-27 23:56 UTC, inlined reviewed
Yeah, I don't know why my lint fixer is adding empty comments. Fixed.

2022-04-28 12:19 UTC, colerogers approved these changes

2022-04-28 18:56 UTC, merged