Fix env file optional params
firebase/firebase-tools pull request #4590
Opened 2022-05-26 07:11 UTC by yamankatby

### Description

Fallback to the default value if the param not required and not provided

fixes https://github.com/firebase/extensions/issues/924

### Scenarios Tested

### Sample Commands

2022-05-30 20:35 UTC, dackers86 requested changes

2022-05-30 20:35 UTC, dackers86 commented on src/extensions/extensionsHelper.ts
> +    if (paramVars[param.param]) continue;
Changes look good. The first line could be an unnecessary change so can probably leave as it was.

2022-06-08 07:49 UTC, yamankatby commented
Hey @bkendall,

done, update test to cover the new case

2022-06-13 16:01 UTC, jeffdh5 approved these changes

2022-06-13 17:07 UTC, joehan requested changes
Thanks for contributing! However, I think this fix is a bit off. The check you removed is correct and should be there - optional params should be null if they are omitted. As I mentioned in the linked issue, I think the extension shoul have those params as required. However, this also highlighted some weirdness in a different check we have: https://github.com/firebase/firebase-tools/blob/master/src/extensions/askUserForParam.ts#L61 is trying to check 'undefined' against the list of options. I'll make a PR to clean that up.

2022-06-13 17:55 UTC, yamankatby commented
Hi @joehan, Thank you for your review!
I made this change to make the behavior of the CLI installation match the Firebase UI installation, In the Firebase UI, you are forced to choose the default value even if the param is optional.

https://user-images.githubusercontent.com/35961879/173414696-a9590145-7fd0-4d22-98e7-916ca0baa871.mov

2022-06-13 18:45 UTC, joehan commented
Hey @yamankatby - the behavior you are describing (being forced to pick a value) is exactly what 'required' is meant to do. 

https://github.com/firebase/firebase-tools/pull/4646 should clean up the errors you were running into where you could not omit optional SELECT and MULTISELECT params. I also suggested in the original thread that we should make these params required.

2022-06-13 18:45 UTC, closed without merging