Fix predeploy hooks not running for framwork deploy with predeploy hook
firebase/firebase-tools pull request #5199
Opened 2022-11-01 09:12 UTC by freakness

### Description

Fixes: https://github.com/firebase/firebase-tools/issues/5159

### Scenarios Tested

This fixes deploying a next.js (or other framework) using predeploy hooks in firebase.json.

2022-12-01 02:46 UTC, jamesdaniels requested changes

2022-12-01 02:46 UTC, jamesdaniels commented on src/deploy/lifecycleHooks.ts
> +      resourceDir = overallOptions.config.path(config.public ?? config.source);
Can you add an entry to the changelog?

2022-12-01 09:15 UTC, freakness commented on src/deploy/lifecycleHooks.ts
> +      resourceDir = overallOptions.config.path(config.public ?? config.source);
Done!

2022-12-01 15:55 UTC, TheIronDev commented
LGTM.

Unrelated to this PR, lifecycleHooks.ts needs tests.

2022-12-01 18:27 UTC, TheIronDev approved these changes

2022-12-02 04:37 UTC, jamesdaniels commented
Merged in #5288, thanks for the fix @freakness

2022-12-02 04:37 UTC, closed without merging