[Fix] Extension extensions not get installed on Windows
firebase/firebase-tools pull request #5371
Opened 2022-12-27 13:07 UTC by stfsy

### Description
On Windows machines, dependencies of firebase extensions do not get installed. Normally node has abstractions for this kind of platform differencies, however, in this case a constructed path was directly passed to `child_process.spawn`. The path was correct for *NIX and did not work on WIN machines. 

### Scenarios Tested
Added a new testcase to verify npm install was executed in the extension's functions directory. 

### Sample Commands

2022-12-27 20:51 UTC, joehan requested changes
The tests are currently failng at the linter. Looks like you need to run `npm run format`

Otherwise, this mostly looks good to me - thanks for the contribution!

2022-12-27 21:50 UTC, stfsy commented on src/emulator/extensionsEmulator.ts
> +import { resolve } from "path";
@joehan thanks for pointing it out. I was able to remove the import as path was already imported actually.

2022-12-27 21:53 UTC, stfsy commented
@joehan thank you i formatted the code and pushed the result.

There is one more open issue not related to my changes

```
> firebase-tools@11.19.0 lint:ts
> eslint --config .eslintrc.js --ext .ts,.js . --fix --quiet

C:\workspace\firebase-tools\src\functional.ts
  55:6  error  'RecursiveElems' is defined but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

2022-12-28 22:46 UTC, joehan approved these changes

2022-12-28 22:46 UTC, joehan commented
Thanks a ton for the contribution! This repo is currently code frozen until the new year, but this will go out in the first release after that.

2022-12-28 22:47 UTC, merged