feat: support extensions with scheduled triggers
firebase/firebase-tools pull request #5373
Opened 2022-12-27 15:50 UTC by stfsy

### Description
Firebase counter extension used a scheduled function to manage shards: https://github.com/firebase/extensions/blob/bb0b6f24479b20c21d3b9da6a9fea518ae66f0aa/firestore-counter/extension.yaml#L47-L56

The `scheduledTrigger` is not supported by the emulator. This PR adds support by converting the scheduled trigger to a pubsub trigger. 

### Scenarios Tested
Manual tests with latest https://github.com/firebase/extensions/tree/master/firestore-counter extension

### Sample Commands

2022-12-27 20:52 UTC, joehan requested changes
This looks mostly good to me. Please run `npm run format` to fix the lint errors.

Thanks for the contribution!

2022-12-27 21:54 UTC, stfsy commented
@joehan thank you i formatted the code and pushed the result.

There is one more open issue not related to my changes

```
> firebase-tools@11.19.0 lint:ts
> eslint --config .eslintrc.js --ext .ts,.js . --fix --quiet

C:\workspace\firebase-tools\src\functional.ts
  55:6  error  'RecursiveElems' is defined but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

2022-12-28 22:44 UTC, joehan approved these changes

2022-12-28 22:45 UTC, joehan commented
Thanks a ton for the contribution! This repo is currently code frozen until the new year, but this will go out in the next release after that

2022-12-28 22:45 UTC, merged