Added status header for query upload requests
firebase/firebase-tools pull request #5425
Opened 2023-01-13 23:05 UTC by maneesht

Fixes #5412

2023-01-17 18:49 UTC, tonyjhuang requested changes

2023-01-17 18:49 UTC, tonyjhuang commented on scripts/storage-emulator-integration/conformance/firebase.endpoints.test.ts
> +        queryUploadStatus = await supertest(firebaseHost)
please create a new test, go/refactoring/test-one-thing-at-a-time

2023-01-17 18:49 UTC, tonyjhuang commented on scripts/storage-emulator-integration/conformance/firebase.endpoints.test.ts
> +        const queryUploadStatus = await supertest(firebaseHost)
please create a new test, go/refactoring/test-one-thing-at-a-time

2023-01-17 18:49 UTC, tonyjhuang commented on scripts/storage-emulator-integration/conformance/firebase.endpoints.test.ts
> +          // No Authorization required in finalize
remove

2023-01-17 18:49 UTC, tonyjhuang commented on scripts/storage-emulator-integration/conformance/firebase.endpoints.test.ts
> +          // No Authorization required in finalize
remove

2023-01-17 18:49 UTC, tonyjhuang commented on scripts/storage-emulator-integration/conformance/firebase.endpoints.test.ts
> +        let queryUploadStatus = await supertest(firebaseHost)
please create a new test, go/refactoring/test-one-thing-at-a-time

2023-01-17 18:49 UTC, tonyjhuang commented on src/emulator/storage/server.ts
> -        "x-goog-upload-status",
why are we removing this?

2023-01-17 18:56 UTC, maneesht commented on src/emulator/storage/server.ts
> -        "x-goog-upload-status",
It's a duplicate :-)

2023-01-18 18:24 UTC, tonyjhuang approved these changes

2023-01-18 18:25 UTC, merged