Discovery: Discover runtime commands.
firebase/firebase-tools pull request #5963
Opened 2023-06-12 14:28 UTC by svnsairam

### Description

### Scenarios Tested

### Sample Commands

2023-06-13 23:46 UTC, taeold requested changes

2023-06-13 23:46 UTC, taeold commented on src/frameworks/compose/discover/runtime/node.ts
> +    const commands: LifecycleCommands = {
nit* probably better to just return directly instead of creating a intermediate variable?

```
return { build: ... }
```

2023-06-15 05:33 UTC, svnsairam commented on src/frameworks/compose/discover/runtime/node.ts
> +
Added the implementation for "yarn".

2023-06-15 05:40 UTC, svnsairam commented on src/frameworks/compose/discover/runtime/node.ts
> +    packageManager: string
These constants are used in different places, having these at the top is helpful.

2023-06-21 19:40 UTC, closed without merging