Vscode emulators
firebase/firebase-tools pull request #6256
Opened 2023-08-15 01:10 UTC by christhompsongoogle

2023-08-16 19:47 UTC, hlshen requested changes

2023-08-16 19:47 UTC, hlshen commented on firebase-vscode/src/workflow.ts
> +  broker.on(
do we want all the emulator registration in workflow (what does workflow mean)? I think the amount of code warrants an emulator.ts file.

2023-08-16 19:47 UTC, hlshen commented on firebase-vscode/src/cli.ts
> +    only: emulatorUiSelections.mode === "hosting" ? "hosting" : ""
can we make an enum for modes? eventually we'll add firemat :)

2023-08-17 17:09 UTC, hsubox76 approved these changes

2023-08-17 17:11 UTC, hsubox76 commented
FYI to Chris and any other reviewers, I can make the modifications we discussed in another PR after this is merged (gate emulators feature based on a VSCode setting, try to find a better solution for the string-replace TODOs), as I know there's some urgency to get the current state of work checked in.

2023-08-21 21:17 UTC, joehan commented on firebase-vscode/src/cli.ts
> +export function listRunningEmulators(): EmulatorInfo[] {
@hlshen this is how we'd grab the port for firemat

2023-08-28 21:29 UTC, merged