App Hosting Emulator Prototype
firebase/firebase-tools pull request #7505
Opened 2024-07-29 20:42 UTC by mathu97

App Hosting Emulator scaffold 
- App Hosting emulator starts up when user runs `firebase emulators:start` if the experiment is enabled and `apphosting` config is set in the `firebase.json` file.
- Currently just runs `npm run dev` under the hood.

2024-09-03 19:53 UTC, tonyjhuang requested changes

2024-09-03 19:53 UTC, tonyjhuang commented on src/emulator/apphosting/index.ts
> +    console.log("starting apphosting emulator");
Let's use EmulatorLogger: https://github.com/firebase/firebase-tools/blob/master/src/emulator/auth/cloudFunctions.ts#L17

2024-09-03 19:53 UTC, tonyjhuang commented on src/emulator/apphosting/index.ts
> +export class AppHostingEmulator implements EmulatorInstance {
docstrings for exported classes, vars, and functions

2024-09-03 19:53 UTC, tonyjhuang commented on src/experiments.ts
> +    shortDescription: "App Hosting emululator",
typo

2024-09-03 20:32 UTC, taeold commented on src/emulator/apphosting/serve.ts
> +  await wrapSpawn("npm", ["run", "dev", "--", `-H`, options.host, `-p`, port], process.cwd());
```suggestion
  await wrapSpawn("npm", ["run", "dev", "--", "-H", options.host, "-p", port], process.cwd());
```

2024-09-03 20:32 UTC, taeold commented on src/emulator/controller.ts
> +  // start after the other emulators
can you extend on why this is the case?

e.g. is it because the service running on app hosting may depend on other emulator, like Firestore?

2024-09-03 20:32 UTC, taeold commented on src/emulator/registry.ts
> +      apphosting: 2.1,
nit* add a brief comment on why it's prioritized here?

2024-09-03 21:24 UTC, milyes commented on src/emulator/apphosting/serve.ts
> +  await wrapSpawn("npm", ["run", "dev", "--", `-H`, options.host, `-p`, port], process.cwd());
"-H"

2024-09-03 21:34 UTC, taeold approved these changes

2024-09-04 18:01 UTC, tonyjhuang approved these changes

2024-09-04 19:21 UTC, merged