Better handling for port conflicts and errors in Data Connect emulator
firebase/firebase-tools pull request #7691
Opened 2024-09-19 23:32 UTC by joehan

### Description
Better handling for port conflicts and errors in Data Connect emulator

### Scenarios Tested
<img width="764" alt="Screenshot 2024-09-19 at 3 51 57 PM" src="https://github.com/user-attachments/assets/a5a3bb34-107b-43ab-9271-44d24fce5d8d">
<img width="1728" alt="Screenshot 2024-09-19 at 3 31 24 PM" src="https://github.com/user-attachments/assets/ba8b0f19-b9e2-409b-bd18-86578d732da9">

2024-09-19 23:37 UTC, yuchenshi commented on src/emulator/downloadableEmulators.ts
> +      await handleEmulatorProcessError(emulator.name, err, command.port);
I don't think this does anything. Event listener callbacks are not monitoring Promise returns and a rejection or a completion won't have visible effects.

To communicate this better, you'd probably want the following instead (this promise is not being handled):

```suggestion
      void handleEmulatorProcessError(emulator.name, err, command.port);
```

2024-09-19 23:37 UTC, yuchenshi commented on src/emulator/storage/rules/runtime.ts
> +      await handleEmulatorProcessError(Emulators.STORAGE, err);
ditto

2024-09-20 00:17 UTC, yuchenshi requested changes
Have we considered automatically picking a pgLite port? I don't feel like requiring an exact port by default is that useful

2024-09-20 00:17 UTC, yuchenshi commented on src/emulator/downloadableEmulators.ts
> +    emulator.instance.on("error", async (err: any) => {
```suggestion
    emulator.instance.on("error", (err: any) => {
```

2024-09-20 00:17 UTC, yuchenshi commented on src/emulator/storage/rules/runtime.ts
> +    this._childprocess.on("error", async (err: any) => {
```suggestion
    this._childprocess.on("error", (err: any) => {
```

2024-09-20 05:50 UTC, joehan commented
> Have we considered automatically picking a pgLite port? I don't feel like requiring an exact port by default is that useful

That's a good point. Switched this to be more similar to the standard behavior of emulators (find a port unless one is set in firebase.json)

2024-09-20 16:50 UTC, yuchenshi approved these changes

2024-09-20 16:50 UTC, yuchenshi commented on src/emulator/dataconnectEmulator.ts
> +        const port = this.args.postgresPort || (await findOpenPort(5432));
This should follow Firestore emulator websocket's example to find a port early and avoid conflicts: https://github.com/firebase/firebase-tools/blob/0314586ffffcfe286caacb067465c1817286c806/src/emulator/controller.ts#L398

I'm approving to unblock but please clean this up as a follow up. Please also remove `findOpenPort` -- it only checks `127.0.0.1`, not `postgresHost`, while the `resolveHostAndAssignPorts` as linked above handles all these edge cases

2024-09-20 16:51 UTC, hlshen approved these changes

2024-09-20 16:55 UTC, merged

2024-09-25 17:23 UTC, yuchenshi commented on src/emulator/dataconnectEmulator.ts
> +        const port = this.args.postgresPort || (await findOpenPort(5432));
Addressed in #7727 (no pun intended)