fix: identify dependencies that might require the --no-tree-shake-icons flag
firebase/firebase-tools pull request #7724
Opened 2024-09-24 14:02 UTC by emwp

…ns flag to build

### Description

### Scenarios Tested

### Sample Commands

2024-09-24 15:08 UTC, leoortizz requested changes

2024-09-24 15:08 UTC, leoortizz commented on src/frameworks/flutter/index.ts
> +export async function build(cwd: string): Promise<BuildResult | undefined> {
the return type didn't change

```suggestion
export async function build(cwd: string): Promise<BuildResult> {
```

2024-09-24 15:08 UTC, leoortizz commented on src/frameworks/flutter/utils.ts
> +    const pubSpecBuffer = await readFile(pubSpecPath);
we should use a path relative to the project root as the project can be located in a subdir, as we do in discover https://github.com/firebase/firebase-tools/blob/cc6744f3e2bbd4fae0d08b1bf4ef999ce5c22fe0/src/frameworks/flutter/index.ts#L16-L20

2024-09-24 15:08 UTC, leoortizz commented on src/frameworks/flutter/utils.ts
> +export async function getTreeShakeFlag(): Promise<string> {
I think we can make it generic like `getAdditionalBuildArgs` and make it return an array of strings, then we can accommodate more use cases in the future if needed

2024-09-24 15:13 UTC, leoortizz commented on src/frameworks/flutter/utils.ts
> +  ];
can you document why we need this? Probably linking to the issue #6197 is good enough

2024-10-08 16:16 UTC, jamesdaniels approved these changes
Thanks. LGTM. Let's add changelog, i'll let @leoortizz shepherd the final approval and merge

2024-10-08 17:32 UTC, leoortizz requested changes

2024-10-08 17:32 UTC, leoortizz commented on src/frameworks/flutter/index.ts
> -  const pubSpec = yaml.parse(pubSpecBuffer.toString());
we still need to return undefined if pubspec or web dir doesn't exist here

2024-10-08 17:52 UTC, leoortizz approved these changes
LGTM!

2024-10-08 17:52 UTC, leoortizz commented on CHANGELOG.md
> +- Parsing pubspec.yaml to detect dependencies that might require the --no-tree-shake-icons flag in order to build. (#7724)
nit: I think we should mention Flutter web in the changelog
```suggestion
- Fixed Flutter web apps that might require --no-tree-shake-icons flag in order to build. (#7724)
```

2024-10-10 22:32 UTC, leoortizz requested changes

2024-10-10 22:32 UTC, leoortizz commented on CHANGELOG.md
> +- Added App Hosting as an option for firebase init. (#7803)
this is part of the previous release https://github.com/firebase/firebase-tools/releases/tag/v13.22.0
```suggestion
```

2024-10-11 04:44 UTC, leoortizz approved these changes

2024-10-11 04:44 UTC, merged