New e2e tests
firebase/firebase-tools pull request #7738
Opened 2024-09-26 09:48 UTC by pr-Mais

### Description

### Scenarios Tested

### Sample Commands

2024-10-09 05:04 UTC, hlshen requested changes

2024-10-09 05:04 UTC, hlshen commented on src/dataconnect/webhook.ts
> +    return await fetch(`http://127.0.0.1:${port}/vscode/notify`, {
was this necessary for the fix?

2024-10-09 05:04 UTC, hlshen commented on firebase-vscode/src/test/integration/empty/init.ts
> +});
I think we're missing a test where we mock the config files loading, and make sure the sidebar loads properly.

2024-10-10 19:47 UTC, pr-Mais commented on firebase-vscode/src/test/integration/fishfood/deploy.ts
> +    expect(args[0][0]).toEqual(`${fbBinary} deploy --only dataconnect`);
I don't think the deployment runs in a task

2024-10-10 19:58 UTC, pr-Mais commented on firebase-vscode/src/test/integration/fishfood/execution.ts
> +    // We need to retry the first execution as it will fail if the emulators hasn't started.
During the test development of this test, that was the case, the sidebar showed emulators as "running" even though the download of dataconnect emulator is still in progress, my connection was a bit slow so it took longer than usual to download.

However, right now it doesn't seem to happen, so I'm wondering if something I pulled from master have fixed the issue.

2024-10-10 20:02 UTC, pr-Mais commented on firebase-vscode/src/core/project.ts
> +          const projects = firstWhereDefined(userScopedProjects as any);
TS was complaining about a mismatch in types, added proper type casting

2024-10-10 20:03 UTC, pr-Mais commented on firebase-vscode/src/data-connect/graphql-syntax-highlighter.ts
> +  const firebaseExt = "myExtension";
my bad, changed to default config

2024-10-10 20:38 UTC, pr-Mais commented on src/dataconnect/webhook.ts
> +    return await fetch(`http://127.0.0.1:${port}/vscode/notify`, {
Nope! reverted it

2024-10-11 21:05 UTC, hlshen commented on firebase-vscode/src/test/integration/fishfood/deploy.ts
> +    expect(args[0][0]).toEqual(`${fbBinary} deploy --only dataconnect`);
Oh.. it might run in a terminal instead of a task. That should be updated, but no AI from your end.

2024-10-11 21:06 UTC, hlshen commented on firebase-vscode/src/test/integration/fishfood/execution.ts
> +    // We need to retry the first execution as it will fail if the emulators hasn't started.
Yes we likely fixed it. Can you try cleaning up this test ?

2024-10-15 09:05 UTC, pr-Mais commented on firebase-vscode/src/test/integration/fishfood/graphql.ts
> +      expect(editorContent).toHaveText(`mutation {
It didn't seem to break, pulled and test passed without updates

2024-10-16 19:07 UTC, hlshen approved these changes

2024-10-28 22:54 UTC, merged